#!/bin/bash

set -e

project="`readlink -f .`"

# Change the env below!
ndk_home=??

toolchain_file=$ndk_home/build/cmake/android.toolchain.cmake

cd app/src/main/cpp; mkdir build 2>/dev/null || true; cd build
cmake -DCMAKE_TOOLCHAIN_FILE="$toolchain_file" \
  -DANDROID_ABI=arm64-v8a \
  -DANDROID_PLATFORM=android-29 \
  -G Ninja ..
ninja

# assert `libmyLib.so` is present now
ls libmyLib.so

# Build and manually put them into `app/libs` folder.
cd "$project"
mkdir app/libs/arm64-v8a -p 2>/dev/null || true
cp -v app/src/main/cpp/build/*.so app/libs/arm64-v8a

# pack the App.
./gradlew asD

echo; echo; echo
echo 'Now inspect app/build/outputs/apk/debug/app-debug.apk,'
echo 'decompress it, `libmyLib.so` is in the `lib` folder, which'
echo 'is expected.'

